name: Deploy Project

on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: npm run build
